apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client
          env:
            - name: SERVER_HOST
              value: server-deployment
            - name: SERVER_PORT
              value: "8080"
